function createfigure(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 03-Nov-2016 22:12:32

% Create figure
figure1 = figure('InvertHardcopy','off','Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

PaperUnits = 'inches';
PaperPosition = [0 0 16 9];

% Create loglog
loglog(X1,Y1,'LineWidth',3);

% Create xlabel
xlabel('Frequency (Hz)');

% Create ylabel
ylabel('Gain');

%% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[50 20000]);
%% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes1,[0.1 10]);
%% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes1,[-1 1]);
box(axes1,'on');
grid(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',21.3333333333333,'LineWidth',2,'XMinorTick','on',...
    'XScale','log','YMinorTick','on','YScale','log');

print('derp', '-dpng', '-r0')
